channels:
- conda-forge
dependencies:
- python=3.12.8
- pip<=24.3.1
- pip:
  - mlflow==2.20.3
  - catboost==1.2.7
  - ipython==9.0.0
  - numpy==1.26.4
  - pandas==2.2.3
  - scipy==1.15.2
name: mlflow-env
